### ISSUE TITLE
Addition to open_clip

### ISSUE THREAD

**Issue by HAlirezaFatemiH** [visheratin/nllb-clip#1]
Hi. 
This is amazing work! Do you plan to add this to open_clip and train with more data? Have you also compared this to xlm-roberta-base-ViT-B-32 and xlm-roberta-large-ViT-H-14 models in open_clip?

**Comment by visheratin** [comment]
Hi! 

Thank you very much!

Yes, I plan to add NLLB-CLIP to the open_clip repo. I just created a [request](https://github.com/huggingface/transformers/issues/26113) to bring NLLB-CLIP to HF transformers and refactored the code to be compatible with the [hub](https://huggingface.co/visheratin/nllb-clip-large). Next, I will probably create a PR to the open_clip repo with the same code until NLLB-CLIP is integrated into transformers. Hopefully, I'll manage to do it this week.

Regarding comparisons, I didn't compare NLLB-CLIP to xlm-roberta-base-ViT-B-32 and xlm-roberta-large-ViT-H-14, only multilingual CLIP. Generally, NLLB-CLIP performs slightly worse than SOTA models on high-resource languages but much better on low-resource ones.
